[project]
name = "videohosting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
]
